name: Build (and optionally Deploy) the Blog Website

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  # Build the website
  build:
    runs-on: ubuntu-latest
    env:
      JEKYLL_ENV: production
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          submodules: recursive

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3
      
      - name: Build Site
        run: |
          bundle exec jekyll build # defaults output to './_site'

      # This will automatically upload an artifact from the './_site' directory
      - name: Upload artifact
        if: ${{ success() }}
        uses: actions/upload-pages-artifact@v2
  
  # Deployment job
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.ref == 'refs/heads/main' }}
    
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
