name: Build and Deploy to Github Pages

on:
  workflow_run:
    workflows: [Build the Blog]
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    env:
      JEKYLL_ENV: production
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      # Use GitHub Actions' cache to cache dependencies on servers
      - uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      # Use GitHub Deploy Action to build and deploy to Github
      - uses: jeffreytse/jekyll-deploy-action@v0.4.0
        with:
          provider: "github"
          token: ${{ secrets.GITHUB_TOKEN }} # It's your Personal Access Token (PAT)
          branch: "gh-pages"
