name: Lint Code Base

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - uses: xt0rted/markdownlint-problem-matcher@v3
      
      - name: Install Markdownlint
        run: npm install -g markdownlint-cli
        
      - run: markdownlint -c .markdownlint.jsonc '_posts/*.md' 
